version: "3.8"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/lib:/home/user/app/lib
      - ./backend/priv:/home/user/app/priv
      - ./backend/test:/home/user/app/test
      - ./backend/config:/home/user/app/config
      - ./backend/.formatter.exs:/home/user/app/.formatter.exs
      - ./backend/mix.exs:/home/user/app/mix.exs
      - ./backend/mix.lock:/home/user/app/mix.lock
      - elixir_deps:/home/user/app/deps
      - elixir_build:/home/user/app/_build

    ports:
      - 4000:4000

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s

  entrypoint:
    image: "busybox:latest"
    depends_on:
      backend:
        condition: service_healthy

volumes:
  node_modules_cache_frontend:
  elixir_deps:
  elixir_build:
