ARG ELIXIR_VERSION=1.14.5
ARG OTP_VERSION=26.0
ARG ALPINE_VERSION=3.18.0

ARG IMAGE="hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-alpine-${ALPINE_VERSION}"

FROM ${IMAGE}

RUN apk update \
    && apk add --no-cache \
    git \
    curl \
    inotify-tools \
    build-base 

# Install hex and rebar
RUN mix local.rebar --force && \
    mix local.hex --force

ENV APP_HOME /home/user/app
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

ENTRYPOINT ["/bin/sh", "-c", "mix deps.get && mix phx.server"]
